# Generated by Boost 1.86.0

# address-model=64

if(CMAKE_SIZEOF_VOID_P EQUAL 4)
  _BOOST_SKIPPED("boost_charconv.lib" "64 bit, need 32")
  return()
endif()

# layout=system

# toolset=vc170

# link=shared

if(DEFINED Boost_USE_STATIC_LIBS)
  if(Boost_USE_STATIC_LIBS)
    _BOOST_SKIPPED("boost_charconv.lib" "shared, Boost_USE_STATIC_LIBS=${Boost_USE_STATIC_LIBS}")
    return()
  endif()
else()
  if(WIN32 AND NOT _BOOST_SINGLE_VARIANT)
    _BOOST_SKIPPED("boost_charconv.lib" "shared, default on Windows is static, set Boost_USE_STATIC_LIBS=OFF to override")
    return()
  endif()
endif()

# runtime-link=shared

if(Boost_USE_STATIC_RUNTIME)
  _BOOST_SKIPPED("boost_charconv.lib" "shared runtime, Boost_USE_STATIC_RUNTIME=${Boost_USE_STATIC_RUNTIME}")
  return()
endif()

# runtime-debugging=off

if(Boost_USE_DEBUG_RUNTIME)
  _BOOST_SKIPPED("boost_charconv.lib" "release runtime, Boost_USE_DEBUG_RUNTIME=${Boost_USE_DEBUG_RUNTIME}")
  return()
endif()

# threading=multi

# variant=release

if(NOT "${Boost_USE_RELEASE_LIBS}" STREQUAL "" AND NOT Boost_USE_RELEASE_LIBS)
  _BOOST_SKIPPED("boost_charconv.lib" "release, Boost_USE_RELEASE_LIBS=${Boost_USE_RELEASE_LIBS}")
  return()
endif()

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "  [x] boost_charconv.lib")
endif()

# Create imported target Boost::charconv

if(NOT TARGET Boost::charconv)
  add_library(Boost::charconv SHARED IMPORTED)

  set_target_properties(Boost::charconv PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_BOOST_INCLUDEDIR}"
    INTERFACE_COMPILE_DEFINITIONS "BOOST_CHARCONV_NO_LIB"
  )
endif()

# Target file name: boost_charconv.lib

get_target_property(__boost_imploc Boost::charconv IMPORTED_IMPLIB_RELEASE)
if(__boost_imploc)
  message(SEND_ERROR "Target Boost::charconv already has an imported location '${__boost_imploc}', which is being overwritten with '${_BOOST_LIBDIR}/boost_charconv.lib'")
endif()
unset(__boost_imploc)

set_property(TARGET Boost::charconv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)

set_target_properties(Boost::charconv PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE CXX
  IMPORTED_IMPLIB_RELEASE "${_BOOST_LIBDIR}/boost_charconv.lib"
  )

set_target_properties(Boost::charconv PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_BOOST_LIBDIR}/boost_charconv.dll"
  )

set_target_properties(Boost::charconv PROPERTIES
  MAP_IMPORTED_CONFIG_MINSIZEREL Release
  MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
  )

set_property(TARGET Boost::charconv APPEND
  PROPERTY INTERFACE_COMPILE_DEFINITIONS "BOOST_CHARCONV_DYN_LINK"
  )

list(APPEND _BOOST_CHARCONV_DEPS headers)
