if (NOT PYTHON_CONFIG_SUFFIX)
    message(STATUS "Shiboken6Config: Using default python: .cp311-win_amd64")
    SET(PYTHON_CONFIG_SUFFIX .cp311-win_amd64)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/Shiboken6Config${PYTHON_CONFIG_SUFFIX}.cmake")
