if (NOT PYTHON_CONFIG_SUFFIX)
    message(STATUS "PySide6QmlConfig: Using default python: .cp311-win_amd64")
    SET(PYTHON_CONFIG_SUFFIX .cp311-win_amd64)
endif()
include(${CMAKE_CURRENT_LIST_DIR}/PySide6QmlConfig${PYTHON_CONFIG_SUFFIX}.cmake)
